version: '3.3'
services:
  service1:
    build: ./service1
    links:
      - db
    image: andreasandrews/service1
    deploy:
      replicas: 2
    ports:
      - protocol: tcp
        published: 5000
        target: 5000

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro


  service2:
    build: ./service2
    image: andreasandrews/service2
    deploy:
      replicas: 2
    ports:
       - protocol: tcp
         published: 5002
         target: 5002

  service3:
    build: ./service3
    image: andreasandrews/service3
    deploy:
      replicas: 2
    ports:
      - protocol: tcp
        published: 5003
        target: 5003

  service4:
    build: ./service4
    image: andreasandrews/service4
    deploy:
      replicas: 2
    ports:
      - protocol: tcp
        published: 5004
        target: 5004
